---
# tasks file for ansible-elastic-heartbeat
- include_tasks: "{{ ansible_os_family }}.yml"
  tags:
    - install-packages

- name: Install Heartbeat
  package:
    name: heartbeat-elastic
    state: present
  notify: restart_heartbeat
  tags:
    - install-packages
  become: True

- name: Copy Heartbeat configuration.
  template:
    src: heartbeat.yml.j2
    dest: "/etc/heartbeat/heartbeat.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart_heartbeat
  become: True
